import os
from dotenv import load_dotenv

load_dotenv()

DEFAULT_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8888",
    "http://localhost:8888",
]

DEFAULT_PORTFOLIO_BOOK_PATH = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "data", "institutional_portfolio.json")
)


def parse_origins(value: str) -> list[str]:
    origins = [item.strip() for item in value.split(",") if item.strip()]
    if not origins or "*" in origins:
        return DEFAULT_ALLOWED_ORIGINS.copy()
    return origins


def parse_bool(value: str) -> bool:
    return value.strip().lower() in {"1", "true", "yes", "on"}


class Settings:
    # API Keys
    TUSHARE_TOKEN: str = os.getenv("TUSHARE_TOKEN", "")
    FRED_API_KEY: str = os.getenv("FRED_API_KEY", "")
    SERVERCHAN_SENDKEY: str = os.getenv("SERVERCHAN_SENDKEY", "")
    QQ_MAIL_USER: str = os.getenv("QQ_MAIL_USER", "")
    QQ_MAIL_PASS: str = os.getenv("QQ_MAIL_PASS", "")
    DEEPSEEK_API_KEY: str = os.getenv("DEEPSEEK_API_KEY", "")

    # Quantitative Thresholds
    TNX_LOOSE_THRESH: float = 3.8
    TNX_TIGHT_THRESH: float = 4.5
    VIX_CAUTION_THRESH: float = 20.0
    VIX_PANIC_THRESH: float = 30.0
    CORR_DUAL_KILL_THRESH: float = 0.15

    # System Settings
    CACHE_TTL: int = 3600
    PORTFOLIO_BOOK_PATH: str = os.getenv("PORTFOLIO_BOOK_PATH", DEFAULT_PORTFOLIO_BOOK_PATH)
    MAX_REQUESTS_PER_MINUTE: int = int(os.getenv("MAX_REQUESTS_PER_MINUTE", "240"))
    ALLOWED_ORIGINS: list[str] = parse_origins(os.getenv("ALLOWED_ORIGINS", ""))
    ALLOW_CREDENTIALS: bool = parse_bool(os.getenv("ALLOW_CREDENTIALS", "false"))

    # ── Calibrated Institutional Parameters ──────────────────
    # Generated by calibrate_params.py against 18-year backtest.
    # Override via env vars if recalibrated.
    CALIBRATED_ALLOW_MIN: int = int(os.getenv("CALIB_ALLOW_MIN", "80"))
    CALIBRATED_LIMITED_MIN: int = int(os.getenv("CALIB_LIMITED_MIN", "60"))
    CALIBRATED_VAR_HIGH: float = float(os.getenv("CALIB_VAR_HIGH", "-6.0"))
    CALIBRATED_VAR_MEDIUM: float = float(os.getenv("CALIB_VAR_MEDIUM", "-1.0"))
    CALIBRATED_EQUITY_VOL: float = float(os.getenv("CALIB_EQUITY_VOL", "0.016"))
    CALIBRATED_BOND_VOL: float = float(os.getenv("CALIB_BOND_VOL", "0.007"))
    CALIBRATED_GOLD_VOL: float = float(os.getenv("CALIB_GOLD_VOL", "0.012"))

    # ── Calibrated Allocation Policy Parameters ─────────────
    CALIBRATED_MAX_STEP_WEIGHT: float = float(os.getenv("CALIB_MAX_STEP", "0.04"))
    CALIBRATED_MAX_SINGLE_WEIGHT: float = float(os.getenv("CALIB_MAX_SINGLE", "0.22"))
    CALIBRATED_MAX_TURNOVER: float = float(os.getenv("CALIB_MAX_TURNOVER", "0.16"))
    CALIBRATED_MAX_GOLD_WEIGHT: float = float(os.getenv("CALIB_MAX_GOLD", "0.22"))

settings = Settings()
